### ISSUE TITLE
How do we activate it for Nushell?

### ISSUE THREAD

**Issue by bearcatsandor** [AndrewAmmerlaan/command-not-found-gentoo#3]
Is there a method for installing this for nushell, or other non-posix shells like fish?

**Comment by Nowa-Ammerlaan** [comment]
Probably yes,

Fish recognizes the `fish_command_not_found` function. If I understand the [documentation](https://fishshell.com/docs/current/cmds/fish_command_not_found.html) correctly, this should do the trick:
```
function fish_command_not_found
    /usr/bin/command-not-found $argv
end
```

Nushell also supports a `command_not_found` [hook](https://www.nushell.sh/book/hooks.html#changing-how-output-is-displayed), something like this should work:
```
$env.config = {
    ...other config...

    hooks: {
        ...other hooks...

        command_not_found: {
            |cmd_name| (
                try {
                    /usr/bin/command-not-found $cmd_name
                }
            )
        }
    }
}
```

However, I have never used these shells so I am unfamiliar with how the ebuild should install this to insert the right function into the environment. If you could test this and let me know what works, then I can adjust the ebuild as required. Basically all that is required is for the shell to call `/usr/bin/command-not-found` with as arguments the command line that has the missing command as the first argument.

**Comment by bearcatsandor** [comment]
Thank you! That's awesome.  With that hook in place, I get both!

![cnf-output](https://github.com/AndrewAmmerlaan/command-not-found-gentoo/assets/57407/ed5e2ca9-2528-4009-89dc-dfd3bb2474e8)

**Comment by bearcatsandor** [comment]
The hooks in the response work well. Thank you!

**Comment by Nowa-Ammerlaan** [comment]
> The hooks in the response work well. Thank you!

Great, thanks for letting me know. I added these instructions to the `README.md` for future reference.
