### ISSUE TITLE
Kind of sanity check before sending requests

### ISSUE THREAD

**Issue by bananas-repos** [AndrewAmmerlaan/command-not-found-gentoo#4]
Hi there.

I find requests in the logs against pfl which do come from the command not found, which could be ignored at the first place.

Examples

```
[WARN] Invalid query GET : '/bin/x~'
[WARN] Invalid query GET : '/usr/bin/x~'
[WARN] Invalid query GET : '/sbin/x~'
[WARN] Invalid query GET : '/usr/sbin/x~'
[WARN] Invalid query GET : '/opt/bin/x~'
[WARN] Invalid query GET : '/bin/x~fdfsf'
[WARN] Invalid query GET : '/usr/bin/x~fdfsf'
[WARN] Invalid query GET : '/sbin/x~fdfsf'
[WARN] Invalid query GET : '/usr/sbin/x~fdfsf'
[WARN] Invalid query GET : '/opt/bin/x~fdfsf'
[WARN] Invalid query GET : '/bin/6~'
[WARN] Invalid query GET : '/usr/bin/6~'
[WARN] Invalid query GET : '/sbin/6~'
[WARN] Invalid query GET : '/usr/sbin/6~'
[WARN] Invalid query GET : '/opt/bin/6~'
[WARN] Invalid query GET : '/bin/5 5'
[WARN] Invalid query GET : '/usr/bin/5 5'
[WARN] Invalid query GET : '/sbin/5 5'
[WARN] Invalid query GET : '/usr/sbin/5 5'
[WARN] Invalid query GET : '/opt/bin/5 5'
[WARN] Invalid query GET : '/bin/5 5'
[WARN] Invalid query GET : '/usr/bin/5 5'
[WARN] Invalid query GET : '/sbin/5 5'
[WARN] Invalid query GET : '/usr/sbin/5 5'
[WARN] Invalid query GET : '/opt/bin/5 5'
[WARN] Invalid query GET : '/bin/~~'
[WARN] Invalid query GET : '/usr/bin/~~'
[WARN] Invalid query GET : '/sbin/~~'
[WARN] Invalid query GET : '/usr/sbin/~~'
```

I do know that everything can be a command and filtering can be complicated, so it is more like a suggestion to think about it.

But one thing is for sure, *everything* will be send to pfl. Sometimes I do have string in the log which should not be there...

**Comment by Nowa-Ammerlaan** [comment]
I think we can add some basic sanity check. For starers we could filter anything that contains the characters `'"~[]{}()!@#$%^&*/\\\t\r\n `. A valid command that we can find on pfl is unlikely to contain these characters. Not sure if we should add `.,` to the list as well, what do you think? Anything else that is missing and should be in the exclusion filter?

**Comment by bananas-repos** [comment]
I would not add those `.,` to the contains list, rather check if those are the only chars and do not send the request.
Also I would check for spaces, or even cut at spaces and send only the part before the first space.

EDIT:
I would add `,` to the contains list, since when does a filename or command has a `,` in it?

**Comment by Nowa-Ammerlaan** [comment]
How does this look: https://github.com/AndrewAmmerlaan/command-not-found-gentoo/commit/c957c6ca148856a31c4f730b3ab3e8a6d533b552 ?  

Instead of a block list, I figured it was easier to make an allow list. The allow list contains `.`, `-`, and `_`. The remaining part of the command must be letters and may contain some numbers as well. However, it may not contain only numbers and it may not start or end with the characters in the allow list.

I think that should cover all cases. Let me know if there is something I missed, if not then I'll release a new version shortly.

**Comment by bananas-repos** [comment]
This looks good. Had to lookup the isalnum and isnumeric methods.

Thank you for accepting the suggestion and keep up the good work.

Cheers and have a wonderful day.
